### PR TITLE
added permission check

### PR DESCRIPTION
**Pull request by policante**
I added a check of permissions to be not requested at all time

### CODE REVIEW

**Comment by Andrew-Quebe** [comment]
Looks great! Thank you :)

**Comment by PDDStudio** [comment]
This is actually not necessary because Android itself will skip those permissions which are already granted.

**Comment by HeinrichReimer** [comment]
@PDDStudio good catch

**Comment by policante** [comment]
but it's not necessary to show always

**Comment by PDDStudio** [comment]
@policante as I said, the Android system will manage this itself and skips the permissions that are already granted. So they won't even be showed.

**Pull request merged**
